kind: ConfigMap
apiVersion: v1
metadata:
  name: smileapp-configmap
data:
  MICRONAUT_APPLICATION_JSON: '{"smileapp": { "apiKey": "818d5136733349908613fc791dd0ce54", "endpoint": "https://wad-face-api.cognitiveservices.azure.com/" } }'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smileapp-deployment
  labels:
    app: smileapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smileapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: smileapp-pod
      labels:
        app: smileapp
    spec:
      containers:
        - name: smileapp
          image: smileapp
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: smileapp-configmap
          ports:
            - containerPort: 50051
              name: "grpc-port"
        - name: envoy
          image: smile/envoy
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: "web"
            - containerPort: 9901
              name: "control"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  type: NodePort
  selector:
    app: smileapp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smileapp-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: envoy-service
              servicePort: 8080
