# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smileservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smileservice.proto',
  package='smileapp',
  syntax='proto3',
  serialized_options=_b('\n\010smileappB\nSmileProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x12smileservice.proto\x12\x08smileapp\"0\n\x0bMoodRequest\x12\x13\n\x0b\x63ontentType\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"F\n\tMoodReply\x12\x0c\n\x04mood\x18\x01 \x01(\t\x12\r\n\x05\x65moji\x18\x02 \x01(\t\x12\x1c\n\x04rect\x18\x03 \x01(\x0b\x32\x0e.smileapp.Rect\";\n\x04Rect\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r2J\n\x0cSmileService\x12:\n\ndetectMood\x12\x15.smileapp.MoodRequest\x1a\x13.smileapp.MoodReply\"\x00\x42\x1e\n\x08smileappB\nSmileProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_MOODREQUEST = _descriptor.Descriptor(
  name='MoodRequest',
  full_name='smileapp.MoodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contentType', full_name='smileapp.MoodRequest.contentType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='smileapp.MoodRequest.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=80,
)


_MOODREPLY = _descriptor.Descriptor(
  name='MoodReply',
  full_name='smileapp.MoodReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mood', full_name='smileapp.MoodReply.mood', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emoji', full_name='smileapp.MoodReply.emoji', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rect', full_name='smileapp.MoodReply.rect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=152,
)


_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='smileapp.Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='smileapp.Rect.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='smileapp.Rect.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='smileapp.Rect.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='smileapp.Rect.height', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=213,
)

_MOODREPLY.fields_by_name['rect'].message_type = _RECT
DESCRIPTOR.message_types_by_name['MoodRequest'] = _MOODREQUEST
DESCRIPTOR.message_types_by_name['MoodReply'] = _MOODREPLY
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoodRequest = _reflection.GeneratedProtocolMessageType('MoodRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOODREQUEST,
  '__module__' : 'smileservice_pb2'
  # @@protoc_insertion_point(class_scope:smileapp.MoodRequest)
  })
_sym_db.RegisterMessage(MoodRequest)

MoodReply = _reflection.GeneratedProtocolMessageType('MoodReply', (_message.Message,), {
  'DESCRIPTOR' : _MOODREPLY,
  '__module__' : 'smileservice_pb2'
  # @@protoc_insertion_point(class_scope:smileapp.MoodReply)
  })
_sym_db.RegisterMessage(MoodReply)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR' : _RECT,
  '__module__' : 'smileservice_pb2'
  # @@protoc_insertion_point(class_scope:smileapp.Rect)
  })
_sym_db.RegisterMessage(Rect)


DESCRIPTOR._options = None

_SMILESERVICE = _descriptor.ServiceDescriptor(
  name='SmileService',
  full_name='smileapp.SmileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=215,
  serialized_end=289,
  methods=[
  _descriptor.MethodDescriptor(
    name='detectMood',
    full_name='smileapp.SmileService.detectMood',
    index=0,
    containing_service=None,
    input_type=_MOODREQUEST,
    output_type=_MOODREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMILESERVICE)

DESCRIPTOR.services_by_name['SmileService'] = _SMILESERVICE

# @@protoc_insertion_point(module_scope)
