# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import smileservice_pb2 as smileservice__pb2


class SmileServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detectMood = channel.unary_unary(
        '/smileapp.SmileService/detectMood',
        request_serializer=smileservice__pb2.MoodRequest.SerializeToString,
        response_deserializer=smileservice__pb2.MoodReply.FromString,
        )


class SmileServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detectMood(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SmileServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detectMood': grpc.unary_unary_rpc_method_handler(
          servicer.detectMood,
          request_deserializer=smileservice__pb2.MoodRequest.FromString,
          response_serializer=smileservice__pb2.MoodReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'smileapp.SmileService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
